

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs: # Esta línea debe estar sin indentación
  enviar_correo: # Indentado 2 espacios bajo jobs:
    runs-on: ubuntu-latest # Indentado al mismo nivel que el nombre del job
    steps: # Indentado al mismo nivel que runs-on:
      - name: Checkout del código # Indentado con un guion y un espacio bajo steps:
        uses: actions/checkout@v4 # Indentado bajo - name: (2 espacios adicionales)

      - name: Obtener Mensaje del Commit
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"             
          echo "El mensaje del commit es: $COMMIT_MESSAGE"
          echo "Enviando correo..."
      
          
    